#!/usr/bin/env bash
# commands to install nginx on web server yep

apt-get update -y
apt-get install -y nginx
sudo ufw allow'80'
sh -c 'echo "Holberton School" > /var/www/html/index.html'
service nginx restart
