#!/usr/bin/env bash
# commands to install nginx on web server yep

apt-get update -y
apt-get install -y nginx
sudo ufw allow'80'
sh -c 'echo "Holberton School" > /var/www/html/index.html'
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://youtu.be/dQw4w9WgXcQ?si=vkl0fr-NMFTC_wtj permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a error_page 404/404.html;' /etc/nginx/sites-available/default
service nginx restart
